"""Mongo Config."""
import os


class MongoConfig:
    """Configuration for Mongo."""

    MONGODB_DB = os.getenv("MONGODB_DB", "StockMarket")
    HOST = os.getenv("MONGODB_HOST", "127.0.0.1")
    PORT = os.getenv("MONGODB_PORT", 27017)
    MONGODB_URI = os.getenv("MONGODB_URI", "mongodb://127.0.0.1:27017/StockMarket")
    ADVANCE_DECLINE = "ADVANCE_DECLINE"
    CUMULATIVE_DERIVATIVES = "CUMULATIVE_DERIVATIVES"
    EQUITY_DERIVATIVES = "EQUITY_DERIVATIVES"
    EXPIRY_DATES = "EXPIRY_DATES"
    EVENTS = "EVENTS"
    FII_DII = "FII_DII"
    HISTORICAL_DERIVATIVES = "HISTORICAL_DERIVATIVES"
    INDEX_DERIVATIVES = "INDEX_DERIVATIVES"
    NIFTY_EQUITY = "NIFTY_EQUITY"
    INDEX_DATA = "INDEX_DATA"
    OPTION_META_DATA = "OPTION_META_DATA"
    TRADING_DATES = "TRADING_DATES"
    ORDERS = "ORDERS"
    POSITIONS = "POSITIONS"
    EQUITY_META = "EQUITY_META"
