"""Trading Bot Utilities Library (tb_utils).

A comprehensive library for algorithmic trading with utilities for
PostgreSQL/TimescaleDB data handling, SQLAlchemy model management,
Pydantic schema validation, and external API integration.
"""

__version__ = "1.15.0"

from .broker.base import (
    BrokerAdapter,
    OrderRequest,
    OrderResult,
    OrderSide,
    OrderStatus,
    OrderType,
    PortfolioPosition,
    TimeInForce,
)
from .config.database import DatabaseConfig, db_settings
from .config.db_session import SessionLocal, get_db
from .greeks import calculate_greeks, calculate_iv_percentile, calculate_iv_rank
from .models import (
    Base,
    BlockDeal,
    Broker,
    BrokerHealthLog,
    BulkDeal,
    Candle,
    CorporateEvent,
    DeliveryData,
    DerivativeTick,
    ExternalApiRequest,
    FiiDii,
    FnoExpiry,
    FundamentalData,
    FundamentalUniverse,
    FuturesOI,
    HistoricalEquityData,
    HistoricalIndexData,
    IndexConstituent,
    IndiaVIX,
    Instrument,
    MarketBreadth,
    News,
    NseIndex,
    OptionChain,
    ParticipantOI,
    Position,
    Recommendation,
    RegimeLog,
    SystemLog,
    SystemMetric,
    Trade,
    TradingHoliday,
    TradingOrder,
    TradingSignal,
    WatchlistFocus,
)
from .request_maker import CircuitBreakerError, RequestMaker
from .risk import ATR_STOP_MULTIPLIER, REGIME_RULES
from .schema import (
    BlockDealResponse,
    BrokerHealthLogResponse,
    BrokerResponse,
    BulkDealResponse,
    CandleResponse,
    CorporateEventResponse,
    DeliveryDataResponse,
    DerivativeMetricsResponse,
    DerivativeTickResponse,
    ExternalApiRequestCreate,
    ExternalApiRequestResponse,
    FiiDiiResponse,
    FnoBanListResponse,
    FnOBuildupResponse,
    FnOBuildupStock,
    FnoExpiryResponse,
    FundamentalDataResponse,
    FuturesOIResponse,
    GenericResponseSchema,
    HistoricalEquityDataResponse,
    HistoricalIndexDataResponse,
    IndexConstituentResponse,
    IndiaVIXResponse,
    InstrumentCreate,
    InstrumentResponse,
    InstrumentUpdate,
    MacroIndicatorResponse,
    MarketBreadthLiveResponse,
    MarketBreadthResponse,
    NewsCreate,
    NewsResponse,
    NewsUpdate,
    Nifty500SmaBreadthResponse,
    NseIndexResponse,
    OptionChainAnalysisResponse,
    OptionChainMetrics,
    OptionChainResponse,
    ParticipantOIResponse,
    PcrHistoryPoint,
    PositionResponse,
    RecommendationCreate,
    RecommendationResponse,
    RegimeLogResponse,
    SpotPriceResponse,
    StrikeDataPoint,
    SystemLogResponse,
    SystemMetricResponse,
    TaskLogSchema,
    TradeResponse,
    TradingHolidayResponse,
    TradingOrderCreate,
    TradingOrderResponse,
    TradingSignalCreate,
    TradingSignalResponse,
    WatchlistFocusResponse,
)
from .telegram import TelegramNotifier, send_telegram_alert
from .utils.enums import (
    BrokerNameEnum,
    BrokerTypeEnum,
    ExecutionModeEnum,
    ExitReasonEnum,
)
from .utils.fno_buildup import FNO_BUILDUP_QUERY, categorize_fno_buildup

__all__ = [
    # Version
    "__version__",
    # Enums
    "BrokerNameEnum",
    "BrokerTypeEnum",
    "ExecutionModeEnum",
    "ExitReasonEnum",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "TimeInForce",
    # Broker Base
    "BrokerAdapter",
    "OrderRequest",
    "OrderResult",
    "PortfolioPosition",
    # Config
    "DatabaseConfig",
    "db_settings",
    "SessionLocal",
    "get_db",
    # Models
    "Base",
    "BlockDeal",
    "Broker",
    "BrokerHealthLog",
    "BulkDeal",
    "Candle",
    "CorporateEvent",
    "DerivativeTick",
    "ExternalApiRequest",
    "FiiDii",
    "FnoExpiry",
    "FundamentalData",
    "FundamentalUniverse",
    "FuturesOI",
    "HistoricalEquityData",
    "HistoricalIndexData",
    "IndexConstituent",
    "Instrument",
    "MarketBreadth",
    "News",
    "NseIndex",
    "OptionChain",
    "Position",
    "SystemLog",
    "SystemMetric",
    "Trade",
    "TradingHoliday",
    "TradingOrder",
    "TradingSignal",
    "IndiaVIX",
    "FuturesOI",
    "ParticipantOI",
    "DeliveryData",
    "RegimeLog",
    "WatchlistFocus",
    "Recommendation",
    # Schemas
    "GenericResponseSchema",
    "BrokerResponse",
    "BrokerHealthLogResponse",
    "ExternalApiRequestCreate",
    "ExternalApiRequestResponse",
    "CorporateEventResponse",
    "TradingHolidayResponse",
    "HistoricalEquityDataResponse",
    "HistoricalIndexDataResponse",
    "CandleResponse",
    "OptionChainResponse",
    "OptionChainAnalysisResponse",
    "OptionChainMetrics",
    "StrikeDataPoint",
    "PcrHistoryPoint",
    "InstrumentResponse",
    "InstrumentCreate",
    "InstrumentUpdate",
    # Market Data
    "FiiDiiResponse",
    "IndiaVIXResponse",
    "FuturesOIResponse",
    "ParticipantOIResponse",
    "DeliveryDataResponse",
    "MarketBreadthResponse",
    "MarketBreadthLiveResponse",
    "Nifty500SmaBreadthResponse",
    "DerivativeMetricsResponse",
    "DerivativeTickResponse",
    "SpotPriceResponse",
    "NewsResponse",
    "NewsCreate",
    "NewsUpdate",
    "BlockDealResponse",
    "BulkDealResponse",
    "FnOBuildupStock",
    "FnOBuildupResponse",
    "MacroIndicatorResponse",
    "FundamentalDataResponse",
    "NseIndexResponse",
    "IndexConstituentResponse",
    "FnoExpiryResponse",
    "FnoBanListResponse",
    "SystemMetricResponse",
    "SystemLogResponse",
    "TaskLogSchema",
    "RegimeLogResponse",
    "WatchlistFocusResponse",
    "TradingSignalCreate",
    "TradingSignalResponse",
    "TradingOrderCreate",
    "TradingOrderResponse",
    "PositionResponse",
    "TradeResponse",
    "RecommendationCreate",
    "RecommendationResponse",
    # Request Maker
    "RequestMaker",
    "CircuitBreakerError",
    # Risk / Position Sizing
    "REGIME_RULES",
    "ATR_STOP_MULTIPLIER",
    # F&O Buildup Utilities
    "FNO_BUILDUP_QUERY",
    "categorize_fno_buildup",
    # Telegram Utilities
    "TelegramNotifier",
    "send_telegram_alert",
    # Option Greeks Utilities
    "calculate_greeks",
    "calculate_iv_rank",
    "calculate_iv_percentile",
]
